FROM timeseries:2.0.1-cuda11.7-cudnn8-devel

RUN pip install jupyter
RUN pip install numpy scikit-learn matplotlib

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip='*'", "--port=8888", "--no-browser", "--allow-root"]

# docker build -f Dockerfile.jupyter -t timeseries:2.0.1-cuda11.7-cudnn8-jupyter .
