FROM python:3.10

RUN --mount=type=cache,target=/root/.cache/pip pip install --upgrade pip

RUN --mount=type=cache,target=/root/.cache/pip pip install affine==2.4.0 attrs==23.1.0 awscli==1.29.42 boto3==1.28.42 botocore==1.31.42 certifi==2023.7.22 click==8.1.7 click-plugins==1.1.1 cligj==0.7.2 cloudpickle==2.2.1 colorama==0.4.4 contextlib2==21.6.0 dill==0.3.7 docutils==0.16 Fiona==1.9.4.post1 gensim==4.3.2 geopandas==0.13.2 google-pasta==0.2.0 importlib-metadata==6.8.0 jmespath==1.0.1 jsonschema==4.19.0 jsonschema-specifications==2023.7.1 multiprocess==0.70.15 numpy==1.25.2 packaging==23.1 pandas==2.1.0 pathos==0.3.1 platformdirs==3.10.0 pox==0.3.3 ppft==1.7.6.7 protobuf==4.24.2 pyasn1==0.5.0 pyparsing==3.1.1 pyproj==3.6.0 pyquadkey2==0.2.2 python-dateutil==2.8.2 pytz==2023.3.post1 PyYAML==6.0.1 rasterio==1.3.8 referencing==0.30.2 rpds-py==0.10.2 rsa==4.7.2 s3transfer==0.6.2 sagemaker==2.184.0 schema==0.7.5 scipy==1.11.2 shapely==2.0.1 six==1.16.0 smart-open==6.4.0 smdebug-rulesconfig==1.0.1 snuggs==1.4.7 tblib==1.7.0 tzdata==2023.3 urllib3==1.26.16 zipp==3.16.2

RUN --mount=type=cache,target=/root/.cache/pip pip install fastparquet tqdm

# DOCKER_BUILDKIT=1 docker build --build-arg BUILDKIT_INLINE_CACHE=1 --platform linux/amd64 -f Dockerfile.preprocess -t timeseries-preprocess .
