FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-devel

RUN --mount=type=cache,target=/root/.cache/pip pip install rasterio==1.3.7 shapely==2.0.1 \
    accelerate==0.20.3 bitsandbytes==0.39.1 einops==0.6.1 transformers==4.30.2 \
    pytorch-metric-learning==2.1.2

RUN --mount=type=cache,target=/var/cache/apt apt update && apt install nano

WORKDIR /workdir

# DOCKER_BUILDKIT=1 docker build --build-arg BUILDKIT_INLINE_CACHE=1 -f Dockerfile.pretrain -t timeseries:2.0.1-cuda11.7-cudnn8-devel .
