FROM pytorch/pytorch:1.13.1-cuda11.6-cudnn8-devel

RUN pip install rasterio==1.3.7 pytorch-metric-learning==2.1.2

WORKDIR /workdir

# docker build -f Dockerfile -t timeseries:1.13.1-cuda11.6-cudnn8-devel .
